language: python
env:
  global:
  - secure: ivg6II471E9HV8xyqnawLIuP/sZ0J63Y+BC0BQcRVKtLn/K3zmD1ozM3TFL9S549Nxd0FqDKHXJvXsgaTGIDpK8sxE2AMKV5IojyM0iAVuN7YjPK9vwSlRw1u0EysPMFqxOZVQnoDyHrSGIUrP/VMdnhBu6dbUX0FyEkvZshXhY=
  - secure: gDWNEYA1EUv4G230/KzcTgcmEST0nf2FeW/z/prsoQBu+TWw1rKKSJAJeMLvuI1z4aYqqNYdmqjWyNhhVK3p5wmFP2lxbhaBT1jDsxxFpePc0nUkdAQOOD0yBpbBGkqkjjxU34HjTX2NFNEbcM3izVVE9oQmS5r4oFFNJgdL91c=
  - secure: RpsZblHFU7a5dnkO/JUgi70RkNJwoUh3jJqVo1oOLjL+lvuAmPXhI8MDk2diUk43X+XCBFBEnm7UCGnjUF+hDnobO4T+VrIFuVJWg3C7iKIT+YWvgG6A+CSeo/P0I0dAeUscTr5z4ylOq3EDx4MFSa8DmoWMmjKTAG1GAeTlY2k=
  - secure: T5OKyd5Bs0nZbUr+YICbThC5GrFq/kUjX8FokzCv7NWsYaUWIwEmMXXzoYALoB3A+rAglOx6GABaupoNKKg3tFQyxXphuMKpZ8MasMAMFjFW0d7wsgGy0ylhVwrgoKzDbCQ5FKbohC+9ltLs+kKMCQ0L+MI70a/zTfF4/dVWO/o=
  - secure: e/8ZAheBZ6BPm2ZSnQ+z+WjS7ce/0znsI7tVq1fY22nTNmyysXQYW3Rx9TOFZkdUm/otZVjqPI4i+3bhx7z89P4xWGK0AtxlUNxaH+Ydw3ivD0LgxFU2m+qsnCCe4p+hQWTigbOkZoFgHbRyksO23haQqgkAtJOEJqg0i2cxCuY=
  - secure: PPweDpaT/uphl0YK6riwfzRlZfAAGmY3bNkboT+cOdP+d2vO855NhVlfSb5yN4UHTOmMeCXOx75RwyLpeuf+p4+3pSX88oVCWGBxctBAnsrFdflMMWxIJRyjGcU7pKfZQg6Z933fVSpLzcg0SwIDVgWgr76ni64OLfKGZAsKO3w=
  - secure: hIyK89iXz1IITMPugoCbV3Ftdc/ExlIoYMfSCBeALydmc8xDz42DE69PDMUHo/ruHLZX7KhsRqOhB/LQ8TlJIO26H6DfvV+jN9YsNoBtbJZglqfvdx0UmywbJ6ylbYhsbOj6hxxBDq+Ud+de6YysUShYSOEyg987W3dnGnyINQ0=
  - secure: HgB7+Zscw2+CHEFi+5kFzWVQ3gh1Hql53dbz974sy3B+wE3Akg8VdpTBxDxXFfS+A5BGstxYmYQu6z6mD8LGt7N7DBcOAJaBSmdxyIeOhnECUcXrKxyJFcpXg/6hMGWrXKEZb7zXJQHk5z2jWywdrA4KmP25XJ6o3dwK7hDC6Fk=
  matrix:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=lint
sudo: false
install:
- travis_retry pip install tox
- travis_retry pip install coveralls
script: tox
after_success:
- if [ $TOXENV == 'py27' ]; then pip install coveralls; coveralls; fi
- if [ $TOXENV == 'py27' ]; then travis_retry pip install scrutinizer-ocular; ocular;
  fi
- if [ $TOXENV == 'py27' ]; then travis_retry pip install scrutinizer-ocular; ocular;
  fi
matrix:
  allow_failures:
  - python: '3.4'
  - python: pypy
  - python: pypy3
  fast_finish: true
